apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-configmap
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
{{ (toYaml .Values.configProperties) | indent 4 }}
