apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-configmap
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  spring.h2.console.enabled: "false"
  management.endpoint.env.show-values: "always"
  management.endpoint.configprops.show-values: "always"
