# Default values for todolist.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sivaprasadreddy/spring-boot-todolist
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30090

postgresql:
  postgresUsername: postgres
  postgresPassword: postgres
  postgresDatabase: appdb
  postgresPort: 5432
