apiVersion: v1
kind: ConfigMap
metadata:
  name: todolist-configmap
  namespace: default
data:
  postgres_host: todolist-postgres-svc
  postgres_port: "5432"
  postgres_database: todolistdb
---
apiVersion: v1
kind: Secret
metadata:
  name: todolist-secrets
type: Opaque
data:
  postgres_username: c2l2YQ== # siva
  postgres_password: c2l2YWxhYnM= # sivalabs
