---
apiVersion: v1
kind: Service
metadata:
  name: todolist-postgres-svc
spec:
  selector:
    app: todolist-postgres-pod
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-postgres-deployment
spec:
  selector:
    matchLabels:
      app: todolist-postgres-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: todolist-postgres-pod
    spec:
      containers:
        - name: postgres
          image: "postgres:16-alpine"
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: postgres_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todolist-configmap
                  key: postgres_database
