apiVersion: v1
kind: Service
metadata:
  name: spring-boot-todolist-svc
spec:
  type: NodePort
  selector:
    app: spring-boot-todolist-pod
  ports:
    - name: app-port-mapping
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-todolist-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-todolist-pod
  template:
    metadata:
      labels:
        app: spring-boot-todolist-pod
    spec:
      containers:
        - name: spring-boot-todolist
          image: sivaprasadreddy/spring-boot-todolist:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todolist-configmap
                  key: postgres_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todolist-configmap
                  key: postgres_port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: todolist-configmap
                  key: postgres_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: postgres_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todolist-secrets
                  key: postgres_password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          volumeMounts:
            - name: config-volume
              mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: todolist-k8s-configmap
