version: '2.2'
services:

  todolist-db:
    image: postgres:12.3
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
